In [2]:
using PorousMaterials, LightGraphs

include("src/moiety.jl")
fragment = moiety("p-phenylene")

xtal = Crystal("IRMOF-1.cif")
strip_numbers_from_atom_labels!(xtal)
infer_bonds!(xtal, true)
xtal.bonds

subgraph = fragment.bonds
graph = xtal.bonds

{424, 384} undirected simple Int64 graph

In [3]:
# "compatibility matrix"
# M₀[α, β] = 1 if any only if:
#     deg(β ∈ graph) ≥ deg(α ∈ subgraph)
#      and
#     species(α ∈ subgraph) == species(β ∈ graph)
function compatibility_matrix(subgraph::SimpleGraph, subgraph_species::Array{Symbol, 1},
                              graph::SimpleGraph,    graph_species::Array{Symbol, 1})::Array{Bool, 2}
    @debug "Finding M₀..."
    # allocate M. rows correspond to subgraph nodes, columns to graph nodes.
    M₀ = zeros(Bool, nv(subgraph), nv(graph))
    for α ∈ 1:nv(subgraph) # Loop over rows (subgraph nodes)
        for β ∈ 1:nv(graph) # Loop over columns (graph nodes)
            # Record Bool for each (i,j): true if atom species match and graph node degree is sufficient.
            if (degree(graph, β) ≥ degree(subgraph, α)) && (subgraph_species[α] == graph_species[β])
                M₀[α, β] = true # cannot rule out correspondence, so, true, for all we know at this point, these could correspond.
            end
        end
    end
    return M₀
end

M₀ = compatibility_matrix(fragment.bonds, fragment.atoms.species, xtal.bonds, xtal.atoms.species)

10×424 Array{Bool,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  1  1  1  1  1  1  1  1  1  1

In [4]:
# list of nodes β ∈ graph that could possibly correpond with node α ∈ subgraph
function candidate_list(M::Array{Bool, 2}, α::Int)::Array{Int, 1}
    return [β for β = 1:size(M, 2) if M[α, β]]
end

cl = candidate_list(M₀, 1)

192-element Array{Int64,1}:
 137
 138
 139
 140
 141
 142
 143
 144
 145
 146
 147
 148
 149
   ⋮
 317
 318
 319
 320
 321
 322
 323
 324
 325
 326
 327
 328

In [5]:
# does node α have possible candidate matches in the graph?
function has_candidates(M::Array{Bool, 2}, α::Int)::Bool
    for β ∈ 1:size(M, 2) # loop over graph nodes
        if M[α, β]
            return true
        end
    end
    # if made it this far, no graph node could possible correspond to α ∈ subgraph =/
    return false 
end

has_candidates (generic function with 1 method)

In [6]:
function is_isomorphism(M::Array{Bool, 2})::Bool
    # (1) each row of M, corresponding to a node α ∈ subgraph, contains exactly one 1.
    #     i.e., every subgraph node has exactly one correspondence
    for α ∈ 1:size(M, 1)
        if sum(M[α, :]) != 1
            return false
        end
    end
    # (2) no column of M, corresponding to a node β ∈ graph, contains more than one 1.
    #     i.e., a graph node does not correspond to more than 1 subgraph node.
    for β ∈ 1:size(M, 2)
        if sum(M[:, β]) > 1
            return false
        end
    end
    # if made it this far, it is indeed an isomorphism.
    return true
end

is_isomorphism(M₀)

false

In [7]:
# idea here:
#   if any subgraph node α has no possible correspondence w/ a node β in the graph, no point in continuing
#   return true iff M has no empty candidate lists for subgraph nodes.
function possibly_contains_isomorphism(M::Array{Bool, 2})::Bool
    @debug "Validating M: $(M)"
    for α ∈ 1:size(M, 1) # loop over subgraph nodes
        if ! has_candidates(M, α)
            return false # subgraph node α cannot be assigned! =-O no point in continuing.
        end
    end
    return true # M may be the intersection of one or more solutions.
end

possibly_contains_isomorphism(M₀)

true

In [8]:
neighbors(xtal.bonds, 1)

0-element Array{Int64,1}

In [9]:
function prune!(M::Array{Bool, 2}, subgraph::SimpleGraph, graph::SimpleGraph)
    pruned = true # to enter while loop
    while pruned
        pruned = false
        for α ∈ size(M, 1) # loop thru subgraph nodes
            # get neighbors of node α
            neighbors_of_α = neighbors(subgraph, α)
            # loop thru candidate matches β ∈ graph for this subgraph node α
            for β ∈ candidate_list(M, α)
                neighbors_of_β = neighbors(graph, β)
                # now, suppose α ∈ subgraph and β ∈ graph correspond...
                for x ∈ neighbors_of_α
                    # if there is no neighbor of β that could correspond to x, neighbor of α, then, contradiction.
                    if length(intersect(candidate_list(M, x), neighbors_of_β)) == 0
                        M[α, β] = false
                        pruned = true
                    end
                end
            end
        end
    end
end

prune!(M₀, fragment.bonds, xtal.bonds)

In [10]:
size(M₀, 1)

10

In [16]:
# suppose node α ∈ subgraph and node β ∈ graph correspond.
#   modify M accordingly.
function assign_correspondence(M::Array{Bool, 2}, α::Int, β::Int)
    M[α, :] .= false # zero out row of subgraph node
    M[:, β] .= false # zero out column of graph node
    M[α, β] = true # assign correspondence at intersection
end

assign_correspondence(M₀, 1, 2)

true

In [14]:
p = 3.0
f(x) = x + p
f(2.0)

5.0

In [ ]:
[is_isomorphism(soln) for soln in solns]